---
title: "Assignment 1"
author: "Umut TURHAN"
date: "21.10.2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# About Me

  Hello! I'm Umut Turhan and I graduated from Business Administration department at METU in 2019. After my graduation, I worked at Vestel about a year as International Sales Specialist, being responsible from the French market. I'm interested in Data Analytics and I would like to specialize in behavioral economics or smart cities concepts. Currently, I research into the possible applications of data analytics for an app targeting free-from market.
  [LinkedIn](https://www.linkedin.com/in/turhanumut/)


# useR!2020
### useR! 2020: themis: dealing with imbalanced data

  When the class distribution of data is skewed and the model cannot differentiate the groups, then the data fails to represent the minorities. In this session, Emil Hvitfeldt begins with a fictional scenario and then highlights the paths to deal with unbalanced data. He mainly address over and under sampling methods to deal with unbalanced data. Through the presentation, he introduces SMOTE algorithm to increase observations from minorities.

[Video Link](https://www.youtube.com/watch?v=kL5qWitjvNg/)

# R posts
### Mapping NBA Shot Locations

  This post is inspired by an article written by a cartographer analyzing NBA players' shots and mapping out some interesting visuals. The original article took data from NBA database and conducted various analysis while visualizing the data on basketball field. The first visual mapped NBA shots by location, showing most shooters tend to have a higher shooting activity around 3-point arc and near the basket. The second visual focused on the success rate by location. In general, it can be inferred that as the shooter gets closer to the basket, the success rate increases on the other hand, the article also drew attention to the fact that shots from different areas in the basketball field have somewhat similar success rate even though some worth 2 points whereas the others worth 3 points. Therefore, the next visual also took points into consideration, showing the map of points per shot, which indicated that if a player is not around the basket then it's better to take the shoot behind 3-point arc since it has similar success rate with those worth 2 points. The final figure combines "points per shot" and "most common locations for shot" into a single map. The article concluded that not surprisingly, the lower success rate areas resulted in as a decrease in the preference of a player for 2 point jump shooting.

"Mapping NBA Shot Locations" takes data from the same database and makes the analysis and visuals with R package called "rayshader".

[Post Link](https://www.r-bloggers.com/2019/06/mapping-nba-shot-locations/)

### How to make interactive maps in R Shiny

  Data visualization can boost a data analysis in many ways. This post is aiming to give tutorial for interactive maps. Earthquake data from USGS is collected and shiny library is introduced.


[Post Link](https://medium.com/@joyplumeri/how-to-make-interactive-maps-in-r-shiny-brief-tutorial-c2e1ef0447da/)

### Using R for Crime Analysis

  Pleasant data analysis over an unpleasant situation. This post gives an overview of the crimes in San Francisco, California with nice visualization tools.
  
  

[Post Link](https://wetlands.io/maps/Crime-Analysis-Using-R.html/)


